[package]
name = "test1"
version = "0.1.0"
authors = ["benjamin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
array2d = "*"
sdl2 = { version = "0.31.0", features = ["bundled", "static-link" ] }
